plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"flashplus" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	minecraft("com.mojang:minecraft:${minecraft_version}")
	mappings loom.layered {
		officialMojangMappings()
	}

	// Fabric Loader and API
	modImplementation("net.fabricmc:fabric-loader:${loader_version}")
	modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")
	include(implementation("org.apache.httpcomponents:httpclient:4.5.14"))
	include(implementation("org.apache.httpcomponents:httpcore:4.4.16"))

	// JiJ MixinExtras if required to be newer than minimum loader-provided version
	// 0.4.1 since 0.16.8
//    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:${mixinextras_version}")))

	// MixinSquared
//	include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${mixinsquared_version}")))

	// ModMenu
//	modImplementation("maven.modrinth:mOgUt4GM:${modmenu_version}")

	// Cloth Config API
//	modApi("me.shedaniel.cloth:cloth-config-fabric:${clothconfig_version}") {
//		exclude(group: "net.fabricmc.fabric-api")
//	}

	// Flashback
	modImplementation("maven.modrinth:4das1Fjq:${flashback_version}")
	include(modImplementation("com.moulberry:lattice:1.3.1"))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}